version: '3'
services:
  db:
    container_name: mydb
    build: ./mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
    - .env
    ports:
      - "3306:3306"
      
  app:
    build: ./emulation
    restart: always
    volumes:
      - ./emulation:/app
    links:
      - "db"
    depends_on:
      - db


volumes:
  db_data: {}
